<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Karyawan;

class KaryawanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Karyawan::create([
            'id_sap' => 10000001,
            'id_nik' => '14050214',
            'nama' => 'Ferdi Iirawan',
            'id_badge' => 10000001,
            'join_date' => '2024-01-24',
            'status_karyawan' => 'Kontrak',
            'foto' => 'C:\\xampp\\tmp\\php5D8F.tmp',
            'no_ktp' => '1405021400000002',
            'tempat_lahir' => 'Pangkalan Kerinci',
            'tanggal_lahir' => '2000-05-15',
            'agama' => 'Islam',
            'jenis_kelamin' => 'Laki-Laki',
            'suku' => 'Jawa',
            'status_kawin' => 'Belum Kawin',
            'jmlh_tanggung' => 'Belum Menikah',
            'kelas_bpjs' => 'Kelas 2',
            'pendidikan' => 'Strata 1',
            'jurusan_pendidikan' => 'Sistem Informasi',
            'nama_sekolahasal' => 'Universitas Riau',
            'tahun_lulus' => '2024',
            'level_karyawan' => 'Rank n File',
            'departemen' => 'Food And Beverage Service',
            'posisi' => 'Waiter',
            'email_pribdi' => 'ferdiimam14@gmail.com',
            'email_kantor' => 'ferdiimam14@gmail.com',
            'no_hp' => '081377683339',
            'no_wa' => '081377683339',
            'riwayat_pelatihan' => 'Training Hospitality',
        ]);

        Karyawan::create([
            'id_sap' => 100000012,
            'id_nik' => '14050214',
            'nama' => 'Budi Setiawan',
            'id_badge' => 10000001,
            'join_date' => '2024-01-24',
            'status_karyawan' => 'Permanen',
            'foto' => 'C:\\xampp\\tmp\\php5D8F.tmp',
            'no_ktp' => '1405021400000002',
            'tempat_lahir' => 'Pangkalan Kerinci',
            'tanggal_lahir' => '2000-05-15',
            'agama' => 'Islam',
            'jenis_kelamin' => 'Laki-Laki',
            'suku' => 'Jawa',
            'status_kawin' => 'Belum Kawin',
            'jmlh_tanggung' => 'Belum Menikah',
            'kelas_bpjs' => 'Kelas 2',
            'pendidikan' => 'Strata 1',
            'jurusan_pendidikan' => 'Sistem Informasi',
            'nama_sekolahasal' => 'Universitas Riau',
            'tahun_lulus' => '2024',
            'level_karyawan' => 'Rank n File',
            'departemen' => 'Food And Beverage Service',
            'posisi' => 'Waiter',
            'email_pribdi' => 'budisetiawan@gmail.com',
            'email_kantor' => 'budisetiawan@gmail.com',
            'no_hp' => '081377683339',
            'no_wa' => '081377683339',
            'riwayat_pelatihan' => 'Training Hospitality',
        ]);

        Karyawan::create([
            'id_sap' => 100000013,
            'id_nik' => '1',
            'nama' => 'Afif Khairi',
            'id_badge' => 10000002,
            'join_date' => '2024-01-24',
            'status_karyawan' => 'Permanen',
            'foto' => '',
            'no_ktp' => '1',
            'tempat_lahir' => 'Pekanbaru',
            'tanggal_lahir' => '2000-05-15',
            'agama' => 'Islam',
            'jenis_kelamin' => 'Laki-Laki',
            'suku' => 'Jawa',
            'status_kawin' => 'Belum Kawin',
            'jmlh_tanggung' => 'Belum Menikah',
            'kelas_bpjs' => 'Kelas 2',
            'pendidikan' => 'Strata 1',
            'jurusan_pendidikan' => 'Management',
            'nama_sekolahasal' => 'Universitas Indonesia',
            'tahun_lulus' => '2024',
            'level_karyawan' => 'GM',
            'departemen' => 'Main',
            'posisi' => 'GM',
            'email_pribdi' => 'afif@gmail.com',
            'email_kantor' => 'afif@gmail.com',
            'no_hp' => '0811',
            'no_wa' => '0811',
            'riwayat_pelatihan' => '',
        ]);

        Karyawan::create([
            'id_sap' => 100000014,
            'id_nik' => '1',
            'nama' => 'Achira Puji Lestari',
            'id_badge' => 10000003,
            'join_date' => '2024-01-24',
            'status_karyawan' => 'Permanen',
            'foto' => '',
            'no_ktp' => '1',
            'tempat_lahir' => 'Pekanbaru',
            'tanggal_lahir' => '2000-05-15',
            'agama' => 'Islam',
            'jenis_kelamin' => 'Laki-Laki',
            'suku' => 'Jawa',
            'status_kawin' => 'Belum Kawin',
            'jmlh_tanggung' => 'Belum Menikah',
            'kelas_bpjs' => 'Kelas 2',
            'pendidikan' => 'Strata 1',
            'jurusan_pendidikan' => 'Management',
            'nama_sekolahasal' => 'Universitas Indonesia',
            'tahun_lulus' => '2024',
            'level_karyawan' => 'Executive Secretary',
            'departemen' => 'Main',
            'posisi' => 'Executive Secretary',
            'email_pribdi' => 'achira@gmail.com',
            'email_kantor' => 'achira@gmail.com',
            'no_hp' => '0811',
            'no_wa' => '0811',
            'riwayat_pelatihan' => '',
        ]);
        Karyawan::create([
            'id_sap' => rand(),
            'id_nik' => '1',
            'nama' => 'Bambang Iswanto',
            'id_badge' => 10000003,
            'join_date' => '2024-01-24',
            'status_karyawan' => 'Permanen',
            'foto' => '',
            'no_ktp' => '1',
            'tempat_lahir' => 'Pekanbaru',
            'tanggal_lahir' => '2000-05-15',
            'agama' => 'Islam',
            'jenis_kelamin' => 'Laki-Laki',
            'suku' => 'Jawa',
            'status_kawin' => 'Belum Kawin',
            'jmlh_tanggung' => 'Belum Menikah',
            'kelas_bpjs' => 'Kelas 2',
            'pendidikan' => 'Strata 1',
            'jurusan_pendidikan' => 'Management',
            'nama_sekolahasal' => 'Universitas Indonesia',
            'tahun_lulus' => '2024',
            'level_karyawan' => 'GMO Head',
            'departemen' => 'Main',
            'posisi' => 'GMO Head',
            'email_pribdi' => 'bambang@gmail.com',
            'email_kantor' => 'bambang@gmail.com',
            'no_hp' => '0811',
            'no_wa' => '0811',
            'riwayat_pelatihan' => '',
        ]);
        Karyawan::create([
            'id_sap' => rand(),
            'id_nik' => '1',
            'nama' => 'Sandy Lee',
            'id_badge' => rand(10000, 100000),
            'join_date' => '2024-01-24',
            'status_karyawan' => 'Permanen',
            'foto' => '',
            'no_ktp' => '1',
            'tempat_lahir' => 'Pekanbaru',
            'tanggal_lahir' => '2000-05-15',
            'agama' => 'Islam',
            'jenis_kelamin' => 'Laki-Laki',
            'suku' => 'Jawa',
            'status_kawin' => 'Belum Kawin',
            'jmlh_tanggung' => 'Belum Menikah',
            'kelas_bpjs' => 'Kelas 2',
            'pendidikan' => 'Strata 1',
            'jurusan_pendidikan' => 'Management',
            'nama_sekolahasal' => 'Universitas Indonesia',
            'tahun_lulus' => '2024',
            'level_karyawan' => 'Front Office',
            'departemen' => 'Main',
            'posisi' => 'Front Office',
            'email_pribdi' => 'sandy@gmail.com',
            'email_kantor' => 'sandy@gmail.com',
            'no_hp' => '0811',
            'no_wa' => '0811',
            'riwayat_pelatihan' => '',
        ]);
        Karyawan::create([
            'id_sap' => rand(),
            'id_nik' => '1',
            'nama' => 'Ade Saputra',
            'id_badge' => rand(10000, 100000),
            'join_date' => '2024-01-24',
            'status_karyawan' => 'Permanen',
            'foto' => '',
            'no_ktp' => '1',
            'tempat_lahir' => 'Pekanbaru',
            'tanggal_lahir' => '2000-05-15',
            'agama' => 'Islam',
            'jenis_kelamin' => 'Laki-Laki',
            'suku' => 'Jawa',
            'status_kawin' => 'Belum Kawin',
            'jmlh_tanggung' => 'Belum Menikah',
            'kelas_bpjs' => 'Kelas 2',
            'pendidikan' => 'Strata 1',
            'jurusan_pendidikan' => 'Management',
            'nama_sekolahasal' => 'Universitas Indonesia',
            'tahun_lulus' => '2024',
            'level_karyawan' => 'Transport',
            'departemen' => 'Main',
            'posisi' => 'Transport',
            'email_pribdi' => 'ade@gmail.com',
            'email_kantor' => 'ade@gmail.com',
            'no_hp' => '0811',
            'no_wa' => '0811',
            'riwayat_pelatihan' => '',
        ]);
        Karyawan::create([
            'id_sap' => rand(),
            'id_nik' => '1',
            'nama' => 'Antoni',
            'id_badge' => rand(10000, 100000),
            'join_date' => '2024-01-24',
            'status_karyawan' => 'Permanen',
            'foto' => '',
            'no_ktp' => '1',
            'tempat_lahir' => 'Pekanbaru',
            'tanggal_lahir' => '2000-05-15',
            'agama' => 'Islam',
            'jenis_kelamin' => 'Laki-Laki',
            'suku' => 'Jawa',
            'status_kawin' => 'Belum Kawin',
            'jmlh_tanggung' => 'Belum Menikah',
            'kelas_bpjs' => 'Kelas 2',
            'pendidikan' => 'Strata 1',
            'jurusan_pendidikan' => 'Management',
            'nama_sekolahasal' => 'Universitas Indonesia',
            'tahun_lulus' => '2024',
            'level_karyawan' => 'Health Club',
            'departemen' => 'Main',
            'posisi' => 'Health Club',
            'email_pribdi' => 'antoni@gmail.com',
            'email_kantor' => 'antoni@gmail.com',
            'no_hp' => '0811',
            'no_wa' => '0811',
            'riwayat_pelatihan' => '',
        ]);
        Karyawan::create([
            'id_sap' => rand(),
            'id_nik' => '1',
            'nama' => 'Abdul Rosyid',
            'id_badge' => rand(10000, 100000),
            'join_date' => '2024-01-24',
            'status_karyawan' => 'Permanen',
            'foto' => '',
            'no_ktp' => '1',
            'tempat_lahir' => 'Pekanbaru',
            'tanggal_lahir' => '2000-05-15',
            'agama' => 'Islam',
            'jenis_kelamin' => 'Laki-Laki',
            'suku' => 'Jawa',
            'status_kawin' => 'Belum Kawin',
            'jmlh_tanggung' => 'Belum Menikah',
            'kelas_bpjs' => 'Kelas 2',
            'pendidikan' => 'Strata 1',
            'jurusan_pendidikan' => 'Management',
            'nama_sekolahasal' => 'Universitas Indonesia',
            'tahun_lulus' => '2024',
            'level_karyawan' => 'House Keeping',
            'departemen' => 'Main',
            'posisi' => 'House Keeping',
            'email_pribdi' => 'abdul@gmail.com',
            'email_kantor' => 'abdul@gmail.com',
            'no_hp' => '0811',
            'no_wa' => '0811',
            'riwayat_pelatihan' => '',
        ]);
        Karyawan::create([
            'id_sap' => rand(),
            'id_nik' => '1',
            'nama' => 'Kurnia Prasetyo',
            'id_badge' => rand(10000, 100000),
            'join_date' => '2024-01-24',
            'status_karyawan' => 'Permanen',
            'foto' => '',
            'no_ktp' => '1',
            'tempat_lahir' => 'Pekanbaru',
            'tanggal_lahir' => '2000-05-15',
            'agama' => 'Islam',
            'jenis_kelamin' => 'Laki-Laki',
            'suku' => 'Jawa',
            'status_kawin' => 'Belum Kawin',
            'jmlh_tanggung' => 'Belum Menikah',
            'kelas_bpjs' => 'Kelas 2',
            'pendidikan' => 'Strata 1',
            'jurusan_pendidikan' => 'Management',
            'nama_sekolahasal' => 'Universitas Indonesia',
            'tahun_lulus' => '2024',
            'level_karyawan' => 'Engineering',
            'departemen' => 'Main',
            'posisi' => 'Engineering',
            'email_pribdi' => 'kurnia@gmail.com',
            'email_kantor' => 'kurnia@gmail.com',
            'no_hp' => '0811',
            'no_wa' => '0811',
            'riwayat_pelatihan' => '',
        ]);
        Karyawan::create([
            'id_sap' => rand(),
            'id_nik' => '1',
            'nama' => 'M. Apriantoro',
            'id_badge' => rand(10000, 100000),
            'join_date' => '2024-01-24',
            'status_karyawan' => 'Permanen',
            'foto' => '',
            'no_ktp' => '1',
            'tempat_lahir' => 'Pekanbaru',
            'tanggal_lahir' => '2000-05-15',
            'agama' => 'Islam',
            'jenis_kelamin' => 'Laki-Laki',
            'suku' => 'Jawa',
            'status_kawin' => 'Belum Kawin',
            'jmlh_tanggung' => 'Belum Menikah',
            'kelas_bpjs' => 'Kelas 2',
            'pendidikan' => 'Strata 1',
            'jurusan_pendidikan' => 'Management',
            'nama_sekolahasal' => 'Universitas Indonesia',
            'tahun_lulus' => '2024',
            'level_karyawan' => 'F&B Product',
            'departemen' => 'Main',
            'posisi' => 'F&B Product',
            'email_pribdi' => 'apriantoro@gmail.com',
            'email_kantor' => 'apriantoro@gmail.com',
            'no_hp' => '0811',
            'no_wa' => '0811',
            'riwayat_pelatihan' => '',
        ]);
        Karyawan::create([
            'id_sap' => rand(),
            'id_nik' => '1',
            'nama' => 'Zaenal Paijo',
            'id_badge' => rand(10000, 100000),
            'join_date' => '2024-01-24',
            'status_karyawan' => 'Permanen',
            'foto' => '',
            'no_ktp' => '1',
            'tempat_lahir' => 'Pekanbaru',
            'tanggal_lahir' => '2000-05-15',
            'agama' => 'Islam',
            'jenis_kelamin' => 'Laki-Laki',
            'suku' => 'Jawa',
            'status_kawin' => 'Belum Kawin',
            'jmlh_tanggung' => 'Belum Menikah',
            'kelas_bpjs' => 'Kelas 2',
            'pendidikan' => 'Strata 1',
            'jurusan_pendidikan' => 'Management',
            'nama_sekolahasal' => 'Universitas Indonesia',
            'tahun_lulus' => '2024',
            'level_karyawan' => 'F&B Service',
            'departemen' => 'Main',
            'posisi' => 'F&B Service',
            'email_pribdi' => 'zaenal@gmail.com',
            'email_kantor' => 'zaenal@gmail.com',
            'no_hp' => '0811',
            'no_wa' => '0811',
            'riwayat_pelatihan' => '',
        ]);
        Karyawan::create([
            'id_sap' => rand(),
            'id_nik' => '1',
            'nama' => 'Suranto',
            'id_badge' => rand(10000, 100000),
            'join_date' => '2024-01-24',
            'status_karyawan' => 'Permanen',
            'foto' => '',
            'no_ktp' => '1',
            'tempat_lahir' => 'Pekanbaru',
            'tanggal_lahir' => '2000-05-15',
            'agama' => 'Islam',
            'jenis_kelamin' => 'Laki-Laki',
            'suku' => 'Jawa',
            'status_kawin' => 'Belum Kawin',
            'jmlh_tanggung' => 'Belum Menikah',
            'kelas_bpjs' => 'Kelas 2',
            'pendidikan' => 'Strata 1',
            'jurusan_pendidikan' => 'Management',
            'nama_sekolahasal' => 'Universitas Indonesia',
            'tahun_lulus' => '2024',
            'level_karyawan' => 'Eco Campy',
            'departemen' => 'Main',
            'posisi' => 'Eco Campy',
            'email_pribdi' => 'suranto@gmail.com',
            'email_kantor' => 'suranto@gmail.com',
            'no_hp' => '0811',
            'no_wa' => '0811',
            'riwayat_pelatihan' => '',
        ]);
        Karyawan::create([
            'id_sap' => rand(),
            'id_nik' => '1',
            'nama' => 'Cliff Malonda',
            'id_badge' => rand(10000, 100000),
            'join_date' => '2024-01-24',
            'status_karyawan' => 'Permanen',
            'foto' => '',
            'no_ktp' => '1',
            'tempat_lahir' => 'Pekanbaru',
            'tanggal_lahir' => '2000-05-15',
            'agama' => 'Islam',
            'jenis_kelamin' => 'Laki-Laki',
            'suku' => 'Jawa',
            'status_kawin' => 'Belum Kawin',
            'jmlh_tanggung' => 'Belum Menikah',
            'kelas_bpjs' => 'Kelas 2',
            'pendidikan' => 'Strata 1',
            'jurusan_pendidikan' => 'Management',
            'nama_sekolahasal' => 'Universitas Indonesia',
            'tahun_lulus' => '2024',
            'level_karyawan' => 'Human Resource',
            'departemen' => 'Main',
            'posisi' => 'Human Resource',
            'email_pribdi' => 'cliff@gmail.com',
            'email_kantor' => 'cliff@gmail.com',
            'no_hp' => '0811',
            'no_wa' => '0811',
            'riwayat_pelatihan' => '',
        ]);
    }
}
